# Autoriser l'accès en lecture seule (rocommunity) avec la string "public"
rocommunity public 127.0.0.1
rocommunity public 10.89.0.0/16

# Informations basiques sur le système
syslocation Laboratoire_Podman
syscontact admin@monlab.local
sysname Fake-Machine-C
sysname 04f438e24b56 
sysname 04f438e24b56 
sysname 04f438e24b56 
sysname M-C 
sysname M-B 
sysname M-A 
sysname M-A 
